"""
Cover Letter Agent
==================
Generates targeted cover letters using a four-slot structure:
  1. Hook       — why this company/role specifically
  2. Why them   — what you admire / why it's a fit
  3. Why you    — 2-3 concrete proof points from experience
  4. CTA        — clear, confident close

Keeps output under 350 words by default.
Uses only the parsed JD fields and resume JSON passed into the prompt (no live web search).
"""

import json
from anthropic import Anthropic

client = Anthropic()

COVER_LETTER_SYSTEM = """You are an expert cover letter writer for technical roles (ML engineering, data science, MLOps).

Write a cover letter following this four-slot structure:
1. HOOK (1-2 sentences): A specific, compelling reason why this company or role caught the candidate's attention. Not generic praise.
2. WHY THEM (2-3 sentences): What the candidate admires about the company's work, mission, or technical approach. Must be specific — reference their actual product, research, or culture signals.
3. WHY YOU (3-4 sentences): 2-3 concrete proof points from the candidate's experience that directly address the JD's requirements. Use numbers where available.
4. CTA (1-2 sentences): Confident, direct close. No "I hope to hear from you" language.

Rules:
- Under 350 words total
- No "I am writing to express my interest in..." openers
- Match the tone to the company culture signals provided
- Return only the letter body (no date, no address block, no "Sincerely")
- Do not invent facts or experience not present in the resume
- Company or product specifics must be grounded in the JOB DESCRIPTION fields below
  (culture_signals, responsibilities, skills, keywords) or in the CANDIDATE JSON — never invent claims
"""


class CoverLetterAgent:
    def __init__(self, resume: dict):
        self.resume = resume

    def _build_candidate_context(self) -> str:
        """Compress relevant resume info for the prompt."""
        r = self.resume
        bullets = []
        for exp in r["experience"]:
            for b in exp["bullets"]:
                bullets.append(f"[{exp['company']} / {exp['title']}] {b['text']}")

        return json.dumps({
            "name": r["contact"]["name"],
            "current_title": r["contact"]["title"],
            "summary": r["summary"]["text"],
            "top_bullets": bullets[:10],
            "skills": {k: v["items"] for k, v in r["skills"].items()},
            "education": [
                f"{e['degree']} {e['field']}, {e['institution']}"
                for e in r["education"]
            ]
        }, indent=2)

    async def run(self, jd: dict, tone: str = "professional-but-direct") -> str:
        """
        Generate a cover letter for a given JD.

        Args:
            jd: Parsed job description dict (from jd_parser)
            tone: Writing tone hint passed to the model

        Returns:
            Cover letter as a markdown string (body only)
        """
        candidate_ctx = self._build_candidate_context()

        jd_ctx = json.dumps({
            "title": jd.get("title"),
            "company": jd.get("company"),
            "location": jd.get("location"),
            "required_skills": jd.get("required_skills", []),
            "preferred_skills": jd.get("preferred_skills", []),
            "responsibilities": jd.get("responsibilities", []),
            "culture_signals": jd.get("culture_signals", []),
            "keywords": jd.get("keywords", [])
        }, indent=2)

        prompt = f"""Write a cover letter for this candidate applying to this role.

CANDIDATE:
{candidate_ctx}

JOB DESCRIPTION:
{jd_ctx}

Tone: {tone}

Grounding: only reference company facts that appear in JOB DESCRIPTION or CANDIDATE above.
"""

        response = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=700,
            system=COVER_LETTER_SYSTEM,
            messages=[{"role": "user", "content": prompt}]
        )

        letter_body = response.content[0].text.strip()

        # Wrap in markdown with metadata header
        company = jd.get("company", "Unknown")
        role = jd.get("title", "Unknown")
        output = f"""# Cover Letter — {role} @ {company}

---

{letter_body}

---
*Generated by CoverLetterAgent | Verify all facts before sending*
"""
        return output
