"""
Cover Letter Agent
==================
Generates targeted cover letters using a four-slot structure:
  1. Hook       — why this company/role specifically
  2. Why them   — what you admire / why it's a fit
  3. Why you    — 2-3 concrete proof points from experience
  4. CTA        — clear, confident close

Keeps output under 350 words by default.
Uses only the parsed JD fields and resume JSON passed into the prompt (no live web search).
"""

import json
from anthropic import AsyncAnthropic

client = AsyncAnthropic()

COVER_LETTER_SYSTEM = """You are an expert cover letter writer for technical roles
(ML engineering, data science, MLOps).

Write a cover letter following this four-slot structure:

1. HOOK (1-2 sentences): A specific, compelling reason why this company or role
   caught the candidate's attention. Not generic praise. Reference something
   concrete — a product decision, a technical approach, a market position.

2. WHY THEM (2-3 sentences): What the candidate admires about the company's work,
   mission, or technical approach. Must be grounded in the JD fields provided
   (culture_signals, responsibilities, product context).
   If culture signals are sparse, focus on the technical problem space or the
   nature of the work described — do not manufacture company-specific claims.

3. WHY YOU (3-4 sentences): 2-3 concrete proof points from the candidate's
   experience that directly address the JD's requirements. Use numbers where
   available. Lead with production and deployment experience — this candidate's
   differentiator is applied ML in real systems (Kubernetes, Docker, PyTorch
   in production), not research publications. Draw from consulting work where
   the candidate owned outcomes across multiple client environments.

4. CTA (1-2 sentences): Confident and direct. Express genuine interest in the
   specific work, and invite a conversation. No "I hope to hear from you" or
   "I would be honored" language.

Rules:
- Under 350 words total
- No "I am writing to express my interest in..." openers
- Match tone to the company culture signals provided; default to
  professional-but-direct if signals are absent
- Return only the letter body (no date, no address block, no "Sincerely")
- Do not invent facts, metrics, tools, or responsibilities not present
  in the resume or JD provided
- Never upgrade the candidate's titles or inflate team sizes
"""


class CoverLetterAgent:
    def __init__(self, resume: dict):
        self.resume = resume

    def _build_candidate_context(self) -> str:
        """Compress relevant resume info for the prompt."""
        r = self.resume
        bullets = []
        for exp in r["experience"]:
            for b in exp["bullets"]:
                bullets.append(f"[{exp['company']} / {exp['title']}] {b['text']}")

        return json.dumps({
            "name": r["contact"]["name"],
            "current_title": r["contact"]["title"],
            "summary": r["summary"]["text"],
            "top_bullets": bullets[:10],
            "skills": {k: v["items"] for k, v in r["skills"].items()},
            "education": [
                f"{e['degree']} {e['field']}, {e['institution']}"
                for e in r["education"]
            ]
        }, indent=2)

    async def run(self, jd: dict, tone: str = "professional-but-direct") -> str:
        """
        Generate a cover letter for a given JD.

        Args:
            jd: Parsed job description dict (from jd_parser)
            tone: Writing tone hint passed to the model

        Returns:
            Cover letter as a markdown string (body only)
        """
        candidate_ctx = self._build_candidate_context()

        jd_ctx = json.dumps({
            "title": jd.get("title"),
            "company": jd.get("company"),
            "location": jd.get("location"),
            "required_skills": jd.get("required_skills", []),
            "preferred_skills": jd.get("preferred_skills", []),
            "responsibilities": jd.get("responsibilities", []),
            "culture_signals": jd.get("culture_signals", []),
            "keywords": jd.get("keywords", [])
        }, indent=2)

        prompt = f"""Write a cover letter for this candidate applying to this role.

CANDIDATE:
{candidate_ctx}

JOB DESCRIPTION:
{jd_ctx}

Tone: {tone}

Grounding: only reference company facts that appear in JOB DESCRIPTION or CANDIDATE above.
"""

        response = await client.messages.create(
            model="claude-sonnet-4-5",
            max_tokens=700,
            system=COVER_LETTER_SYSTEM,
            messages=[{"role": "user", "content": prompt}]
        )

        letter_body = response.content[0].text.strip()

        # Wrap in markdown with metadata header
        company = jd.get("company", "Unknown")
        role = jd.get("title", "Unknown")
        output = f"""# Cover Letter — {role} @ {company}

---

{letter_body}

---
*Generated by CoverLetterAgent | Verify all facts before sending*
"""
        return output
